app = "days-g1kdka"
kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 5000
  protocol = "tcp"
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
  [[services.ports]]
    handlers = ["http"]
    port = 80
